name: Deploy to NPM

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: build
        run: npm run build
      - name: publish
        run: npm publish
